### ISSUE TITLE
Bootstrap Components needs upgrade from 4 to 5

### ISSUE THREAD

**Issue by freephile** [freephile/meza#107]
### Environment

- Machine or Virtual Machine details: Digital Ocean
- Operating System: (`cat /etc/redhat-release`)
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
- meza version hash: (`meza --version`)
Meza 39.7.0-8-g530c3a0
Commit 530c3a0e82c3e7d7a348fadb975331a6074f0659
Mediawiki EZ Admin

### Issue details

```
Deprecated: Premature access to service container [Called from BootstrapComponents\HookRegistry::registerMyConfiguration in /opt/htdocs/mediawiki/extensions/BootstrapComponents/src/HookRegistry.php at line 381] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381

Deprecated: Premature access to service 'HookContainer' [Called from MediaWiki\MediaWikiServices::getInstance in /opt/htdocs/mediawiki/includes/MediaWikiServices.php at line 289] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381

Deprecated: Premature access to service 'ObjectFactory' [Called from Wikimedia\Services\ServiceContainer::{closure} in /opt/htdocs/mediawiki/includes/ServiceWiring.php at line 721] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381

Deprecated: Premature access to service 'ConfigFactory' [Called from BootstrapComponents\HookRegistry::registerMyConfiguration in /opt/htdocs/mediawiki/extensions/BootstrapComponents/src/HookRegistry.php at line 381] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381

Deprecated: Premature access to service 'BootstrapConfig' [Called from Wikimedia\Services\ServiceContainer::{closure} in /opt/htdocs/mediawiki/includes/ServiceWiring.php at line 414] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381
```

**Comment by freephile** [comment]
According to the [Bootstrap Components project page](https://www.mediawiki.org/wiki/Extension:BootstrapComponents), **5.x** is the current series.

The same is true for the [Bootstrap extension](https://github.com/ProfessionalWiki/Bootstrap#installation)


## Solution
Change `~4.0` to `^5.0` for Bootstrap Components
Change `~4.0` to `~5.0` for Bootstrap Extension
 in `MezaLocalExtensions.yml` and then run a deploy. MezaLocalExtensions.yml is found in /opt/conf-meza and should be versioned in your "config" repo.

## Note
> ~ allows last digit specified to go up
> ^ doesn't allow breaking changes

See https://composer.json.jolicode.com/ for a quick cheatsheet on Composer version constraints

## MezaLocalExtensions.yml
So, this is what the new spec should look like
```yaml
- name: Bootstrap
  composer: "mediawiki/bootstrap"
  version: ~5.0
  config: |
    wfLoadExtension( 'Bootstrap' );

#### snip for brevity ###

# Adds Tooltips, Cards, Carousel etc.
- name: BootstrapComponents
  composer: "mediawiki/bootstrap-components"
  version: ^5.0
  config: |
    wfLoadExtension( 'BootstrapComponents' );
```

## Special:Version
### Before
Special:Version showed v4.0.1 was installed
[BootstrapComponents](https://www.mediawiki.org/wiki/Extension:BootstrapComponents)	4.0.1

### After
Can't show 'after' because deploys are failing on Ansible repo not found for **CentOS** Issue #108 

## Compatibility with Universal Language Selector (ULS)
If you use ULS, be sure to add the following CSS to MediaWiki:Common.css on-wiki ([ref](https://github.com/ProfessionalWiki/chameleon/issues/151))
```css
.uls-language-list {
        display: block;
}

.uls-search {
        display: block;
}
```
