### ISSUE TITLE
Symbolic links to support short URLs are not being created.

### ISSUE THREAD

**Issue by freephile** [freephile/meza#115]
### Environment

- Digital Ocean
- Operating System: Rocky Linux release 8.10 (Green Obsidian)
- meza version: Meza 39.8.0-32-g1219d72
Commit 1219d7240e3a7ccdf649b14635783cf6dc20ca6c
Mediawiki EZ Admin

### Issue details

To support SHORT URLs, we create a symbolic link from the 'wiki name' to the 'mediawiki' directory in `/opt/htdocs`. These symlinks are created using `{{ list_of_wikis }}` - an Ansible fact created at about line 461 in `src/roles/mediawiki/tasks/main.yml` At some point the list creation was placed late in the script whereas the symlink creation was early in the script. This meant that symlinks were not being created because the list was empty. Here's an excerpt from `/opt/data-meza/logs/deploy-output/monolith-2024-10-23_212557.log`

```
TASK [mediawiki : Create symlink to core, to enable short urls] ****************
task path: /opt/meza/src/roles/mediawiki/tasks/main.yml:103
skipping: [localhost] => {
    "changed": false,
    "skipped_reason": "No items in the list"
}
```

By moving the symlink creation task to approximately line 489 (after the fact/list creation) symlinks are once again being dutifully created.

```
- name: Create symlink to core, to enable short urls
  file:
    src: "{{ m_mediawiki }}"
    dest: "{{ m_htdocs }}/{{ item }}"
    state: link
  with_items:
    - "{{ list_of_wikis }}"
  tags:
    - latest
```
