### ISSUE TITLE
Add option to install Composer Dev dependencies

### ISSUE THREAD

**Issue by freephile** [freephile/meza#123]
Currently Meza is hard-coded to exclude dev dependencies. If Meza is being deployed in any actual development environment you would obviously want and need dev dependencies. Add a configuration option so that deploys do install dev dependencies.

**Comment by freephile** [comment]
Currently, `composer` is run from the MediaWiki tasks (`src/roles/mediawiki/tasks/main.yml`), where `no_dev` is **hard-coded**.

``` yaml
- name: Run composer update on MediaWiki for dependencies
  become: true
  become_user: "meza-ansible"
  composer:
    command: update
    working_dir: "{{ m_mediawiki }}"
    no_dev: true
  tags:
    - composer-extensions
    - latest
    - skins
```

We could simply change that to a variable.

**Comment by freephile** [comment]
https://docs.ansible.com/ansible/latest/collections/community/general/composer_module.html#parameters

To 'enable' require-dev packages, we need to set 'no_dev' to false. Like this:

```yaml
- name: Run composer update on MediaWiki for dependencies
  become: true
  become_user: "meza-ansible"
  composer:
    command: update
    working_dir: "{{ m_mediawiki }}"
    no_dev: false
  tags:
    - composer-extensions
    - latest
    - skins
```

So, we named the boolean Ansible playbook variable 'm_disable_composer_dev_dependencies'

**m_disable_composer_dev_dependencies: false** will install the require-dev packages.

This makes available all the Development, Linting, PHPUnit packages etc. so development is possible.

Commit in the conf repo: https://github.com/freephile/meza-conf-public/commit/a21cecf0faf7f12ee55b98a8caad14e66427b5ac
