### ISSUE TITLE
Add role for provisioning TLS certificate (certbot / letsencrypt)

### ISSUE THREAD

**Issue by freephile** [freephile/meza#130]
We need a role that provides TLS certificates and automatically renews them.

**[Certbot](https://certbot.eff.org/)** will do this. Thank you [Lets Encrypt](https://letsencrypt.org/)!

Jeff Geerling wrote an [Ansible certbot role](https://github.com/geerlingguy/ansible-role-certbot) for the installation and setup.

I previously created a [certbot role for QualityBox](https://github.com/freephile/qb/tree/main/src/roles/certbot) that integrates with the way that Meza provisions a self-signed cert (meza.pem).

**Comment by freephile** [comment]
We could install with Ansible Galaxy

`ansible-galaxy install geerlingguy.certbot`

or use `requirements.yml` to get it installed (example sources from GitHub instead of Galaxy)

```yaml
  - name: geerlingguy.certbot
    src: https://github.com/geerlingguy/ansible-role-certbot
    version: 5.1.1
```

But since we want to integrate it, it's best to include it in a playbook
