### ISSUE TITLE
Extract role for creating self-signed TLS certificate

### ISSUE THREAD

**Issue by freephile** [freephile/meza#132]
Currently the creation of a self-signed certificate is embedded in the haproxy role. With the completion of Issue #130, the only use-case for a self-signed cert is to run the stack internally or in development (e.g. Vagrant). Do not bind cert generation to the choice of proxy server (even though we love HAProxy) so that the TLS endpoint is easy to configure.

There are many pre-built Ansible roles for creating self-signed TLS certificates.

RedHat's (example below) or [Jim Tarpley](https://galaxy.ansible.com/ui/repo/published/trippsc2/general/content/role/self_signed_certificate/?version=2.12.0)

```yaml
- name: Generate self-signed certificate using system roles
  ansible.builtin.include_role:
    name: redhat.rhel_system_roles.certificate
  vars:
    certificate_requests:
      - name: web-server
        ca: self-sign
        dns: test.example.com
```

But even ***more natively***, you just use the `community.crypto` module [see docs](https://docs.ansible.com/projects/ansible/latest/collections/community/crypto/docsite/guide_selfsigned.html)

```yaml
---
- name: Generate a Self-Signed TLS Certificate
  hosts: localhost
  tasks:
    # Step 1: Generate a private key
    - name: Create private key
      community.crypto.openssl_privatekey:
        path: /etc/ssl/private/ansible.key
        size: 2048
        type: RSA

    # Step 2: Generate the Certificate Signing Request (CSR)
    - name: Create CSR
      community.crypto.openssl_csr:
        path: /etc/ssl/certs/ansible.csr
        privatekey_path: /etc/ssl/private/ansible.key
        common_name: "example.com"

    # Step 3: Generate the Self-Signed Certificate using the CSR
    - name: Create self-signed certificate
      community.crypto.x509_certificate:
        path: /etc/ssl/certs/ansible.crt
        privatekey_path: /etc/ssl/private/ansible.key
        csrpath: /etc/ssl/certs/ansible.csr
        provider: selfsigned
        selfsigned_not_after: "+365d" # Valid for 1 year
```
