### ISSUE TITLE
Remove current GitHub Actions

### ISSUE THREAD

**Issue by freephile** [freephile/meza#2]
### Environment

- Machine or Virtual Machine details: (VirtualBox, VMWare, Digital Ocean, AWS, etc)
Machine independent because this is a DevOps / Repository management issue.

### Issue details

The project currently has a couple stale DevOps workflows that create a build on Ubuntu (because that's the only 'built-in' Linux OS for GitHub Actions). These need to be removed immediately because they will always fail, and they cost money since GitHub Actions are billable to your account.

### Background
> GitHub Actions is a continuous integration and continuous delivery (CI/CD) platform that allows you to automate your build, test, and deployment pipeline. You can create workflows that build and test every pull request to your repository, or deploy merged pull requests to production.

See https://github.com/nasa/meza/commit/591df68c5a8c310462d4723a5e15bbaf4134fead for the commit that introduced the docker-build.yml

### RoadMap
I believe the correct work plan is to remove the current CI/CD and then implement a new CI/CD that reflects the actual needs of the project and target OS/environment. Because the target OS and environment is Rocky Linux (and maybe using VirtualBox for development), the GitHub Actions workflow should be 'self-hosted' and run on the developer machine and/or internal infrastructure when appropriate.

**Comment by freephile** [comment]
[test.yml](https://github.com/nasa/meza/blob/fabcf0c3e4855f57ddbdcc0635bc8e27421494a8/.github/workflows/test.yml)

<details><summary>Details</summary>
<p>
```yaml
name: Test Meza
on:
  push:
    branches:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        test_type:
          - monolith-from-scratch
          - monolith-from-import
          - import-from-remote
          - backup-to-remote
          - import-from-alt-remote

    runs-on: ubuntu-latest

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@master

      - name: apt-get update
        run: sudo apt-get update

      - name: install prereqs
        run: sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common

      - name: get key
        run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

      - name: fingerprint
        run: sudo apt-key fingerprint 0EBFCD88

      - name: Get docker repo
        run: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

      - name: apt-get update again
        run: sudo apt-get update

      - name: Install docker
        run: sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: run test
        run: sudo bash ./tests/docker/run-tests.sh ${{ matrix.test_type }} ${PWD}
```
</p>
</details>

**Comment by freephile** [comment]
[docker-build.yml](https://github.com/nasa/meza/blob/fabcf0c3e4855f57ddbdcc0635bc8e27421494a8/.github/workflows/docker-build.yml)

<details><summary>Details</summary>
<p>
```yaml
name: Docker Build
on:
  push:
    branches: ['master']

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          path: tests/containers/base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: enterprisemediawiki/meza
          tags: base

  build-pre-yum:
    needs: [build-base]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          path: tests/containers/pre-yum
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: enterprisemediawiki/meza
          tags: pre-yum

  build-full:
    needs: [build-pre-yum]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          path: tests/containers/full
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: enterprisemediawiki/meza
          tags: full

  build-max:
    needs: [build-pre-yum]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          path: tests/containers/max
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: enterprisemediawiki/meza
          tags: max
```
</p>
</details>
