### ISSUE TITLE
Restructure Meza into multiple roles and collection(s)

### ISSUE THREAD

**Issue by freephile** [freephile/meza#42]
Accepted best practice is to have each role live in its own git repository. Each role is complete for a given aspect: Apache, PHP, gluster, epel, remi, kibana, haproxy, imagemagick, lua, memcached, netdata, mariadb, mediawiki. Roles should be combined into playbooks and used by other projects as needed. 

Best Practice summarized as

> Better to use ansible-galaxy vs git submodules (ansible-galaxy can be used with any git repositories not just ansible-galaxy content) see https://galaxy.ansible.com/docs/using/installing.html
> One role per repo, individual projects in a separate repo with requirements.yml file pulling roles from their respective repos which could be pinned to a particular git tag etc.
> It can be painful process to take scattered ansible content (especially at large company) and get it into this type of setup so it can all be used together by a large team effectively. The sooner the better from my experience.

https://www.reddit.com/r/ansible/comments/l5v2g8/roles_and_playbook_organization/

Pros:
* makes Meza much more modular
* easier to test / debug each aspect
* able to use 3rd-party roles (e.g. geerlingguy, elasticco, netdata)
* quickly increase support for other mainstream OS: Ubuntu/Debian and even Windows

**Comment by freephile** [comment]
The basic pattern is this:
1. Create a `requirements.yml` file to specify [all the collections and roles](https://galaxy.ansible.com/ui/) you want to use; and the version of those roles.
2. Use the [`ansible-galaxy`](https://docs.ansible.com/projects/ansible/latest/cli/ansible-galaxy.html) cli tool, that comes with ansible, to install those requirements.
3. Create your playbook(s) to reference the collections, roles and tasks that you need.

## For example

```yaml
---
- name: Deploy
  hosts: all
  gather_facts: true
  # ...

  collections:
    # All the collections you'll need

  pre_tasks:
    - name: Install requirements
      delegate_to: localhost
      ansible.builtin.command: ansible-galaxy install -r {{ role_path }}/requirements.yml
    # Other tasks that you run BEFORE the roles

  roles:
    - { role: "roleX", tags: "roleX" }
    # your other (unpublished) roles

  post_tasks:
    # other tasks that you run AFTER the roles

```
more at https://stackoverflow.com/questions/25230376/how-to-automatically-install-ansible-galaxy-roles/35319216
