### ISSUE TITLE
Fix Widgets compiled templates directory permissions

### ISSUE THREAD

**Issue by freephile** [freephile/meza#61]
After commit [383f4c8](https://github.com/freephile/meza/commit/383f4c8a4144cda5c1300080fdac78c94f39c1c2) where the 'compiled templates' directory for the Widgets extension was setup for access by Apache, I'm still seeing errors when doing a deploy.
```
failed: [localhost] (item={'name': 'Widgets', 'repo': 'https://github.com/wikimedia/mediawiki-extensions-Widgets.git',

Local modifications exist in repository (force=no).
```

The error is changed mode which still blocks a git update of the directory.

```
[userx@localhost Widgets]$ sudo git diff
diff --git a/compiled_templates/.htaccess b/compiled_templates/.htaccess
old mode 100644
new mode 100755

```

**Comment by freephile** [comment]
Although we can temporarily solve this with a `overwrite_local_git_changes: true` in `config/defaults.yml`, the proper solution is to move the Apache ownership rule towards the end of the tasks so that the source code in the directory is fully updated; and **then** made writable by apache. 

compiled_templates is already in the .gitignore file for the repo.

**Comment by freephile** [comment]
> compiled_templates is already in the .gitignore file for the repo.
Which brings up a good point. On a **successful** checkout of the Widgets extension, you should already have a compiled_templates directory.
```
git ls-files --format='%(objectmode) %(path)' | grep compiled
100644 compiled_templates/.htaccess
```

The problem really is that the task "Ensure MediaWiki still properly owned" recursively chowns ALL web content with one rule that is not suitable for a directory that needs to be web **writable**. So really, we need to exclude the compiled_templates directory from that task.

Since there is not an 'exclude' option, instead, we'll create a stat register, and be sure to preserve modification and access times for files after they get chowned to apache from meza-ansible on every deploy.

```
- name: Check if the compiled_templates directory exists
  stat:
    path: "{{ m_mediawiki }}/extensions/Widgets/compiled_templates/"
  register: compiled_templates_folder

- name: "Ensure compiled templates folder for widget extension is ownwed by apache"
  file:
    path: "{{ m_mediawiki }}/extensions/Widgets/compiled_templates/"
    owner: apache
    group: apache
    mode: "u=rwX,g=rX,o=rX"
    state: directory
    recurse: true
    modification_time: preserve
    access_time: preserve
  when: compiled_templates_folder.stat.exists
```

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
