### ISSUE TITLE
Syntax check complains about host patterns

### ISSUE THREAD

**Issue by freephile** [freephile/meza#68]
```bash
cd /opt/meza/config
sudo ansible-playbook -i /opt/conf-meza/secret/monolith/hosts /opt/meza/src/playbooks/site.yml --syntax-check
```

[WARNING]: Could not match supplied host pattern, ignoring: exclude-all
[WARNING]: Could not match supplied host pattern, ignoring: load_balancers_nonmeza
[WARNING]: Could not match supplied host pattern, ignoring: load_balancers_nonmeza_external
[WARNING]: Could not match supplied host pattern, ignoring: load_balancers_nonmeza_internal
[WARNING]: Could not match supplied host pattern, ignoring: load_balancers_meza_internal
[WARNING]: Could not match supplied host pattern, ignoring: load_balancers_meza_external

**Comment by freephile** [comment]
If you don't point to a hosts file, here are all the patterns site.yml is using:

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: Could not match supplied host pattern, ignoring: exclude-all
[WARNING]: Could not match supplied host pattern, ignoring: load_balancers_nonmeza
[WARNING]: Could not match supplied host pattern, ignoring: load_balancers_nonmeza_external
[WARNING]: Could not match supplied host pattern, ignoring: load_balancers_nonmeza_internal
[WARNING]: Could not match supplied host pattern, ignoring: load_balancers
[WARNING]: Could not match supplied host pattern, ignoring: load_balancers_meza_internal
[WARNING]: Could not match supplied host pattern, ignoring: load_balancers_meza_external
[WARNING]: Could not match supplied host pattern, ignoring: app_servers
[WARNING]: Could not match supplied host pattern, ignoring: memcached_servers
[WARNING]: Could not match supplied host pattern, ignoring: db_master
[WARNING]: Could not match supplied host pattern, ignoring: db_slaves
[WARNING]: Could not match supplied host pattern, ignoring: backup_servers
[WARNING]: Could not match supplied host pattern, ignoring: elastic_servers
[WARNING]: Could not match supplied host pattern, ignoring: logging_servers

**Comment by freephile** [comment]
This is in the deploy log:
```
Using /opt/meza/config/ansible.cfg as config file
host_list declined parsing /opt/conf-meza/secret/monolith/hosts as it did not pass its verify_file() method
script declined parsing /opt/conf-meza/secret/monolith/hosts as it did not pass its verify_file() method
auto declined parsing /opt/conf-meza/secret/monolith/hosts as it did not pass its verify_file() method
Parsed /opt/conf-meza/secret/monolith/hosts inventory source with ini plugin
```

We should use [the recommended YAML format](https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html) for the example hosts file instead of ini format.

**Comment by freephile** [comment]
This fact format should yield the correct result from the templating:
```yaml
{
  "load_balancers": ["localhost"],
  "app_servers": ["localhost"],
  "memcached_servers": ["localhost"],
  "db_slaves": "", 
  "elastic_servers": ["localhost"],
  "backup_servers": ["localhost"],
  "logging_servers": ["localhost"]
}
```

It looks as though meza.py will generate this data in setup-env function which then calls the setup-env playbook. In the process of the function, the temporary data structure is deleted.  So, the only way to test this function currently is either run the playbook with extra-vars, or run getmeza.sh on a clean guest. A previously setup Meza controller will detect the existence of the hosts file and not run the setup-env playbook. IOW, Meza is very conservative and will not destroy a hosts file that exists because it may have been altered or is already relied upon.

I tested the template and data structure in my [Jinja2 live parser](https://wiki.freephile.org/wiki/Controlling_whitespace_in_Jinja2_templates#By_hand)

producing this result for the hosts file:

```yaml
# Ansible inventory (AKA "hosts") file
#
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
#
# Tell Ansible to use a local connection for localhost
all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    load_balancers:
      hosts:

        localhost:

    app_servers:
      hosts:

        localhost:

    memcached_servers:
      hosts:

        localhost:

    db_master:
      hosts:
        localhost:

    # Note: db_slaves needs to be in the form:
    #   1.2.3.4:
    #     mysql_server_id: 2   # ids must be unique and greater than 1
    db_slaves:
      hosts:

    elastic_servers:
      hosts:

        localhost:

    backup_servers:
      hosts:

        localhost:

    logging_servers:
      hosts:

        localhost:
```

which I was able to successfully test by dropping it in place and running 

`sudo meza deploy monolith -vvv -e group_wheel=wheel -e ansible_user=meza-ansible --list-tasks`
