### ISSUE TITLE
Run meza as non-root user

### ISSUE THREAD

**Issue by freephile** [freephile/meza#72]
Ansible includes 'become' functionality to assume privilege when needed. We should be able to run all of meza without **being** root nor using **sudo** on every command.

Use the proper [playbook privilege escalation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html)  of Ansible.

**Comment by freephile** [comment]
Ansible has the **[become](https://docs.ansible.com/ansible/latest/user_guide/become.html)** module. Use it.

Note: after Ansible 1.9, the _sudo_ module was renamed _become_

Example:
```yaml
- name: check user
  become: yes
  become_user: someusername
  become_method: su
  become_flags: '--login'
  shell: whoami
```

ref. https://serverfault.com/questions/662443/running-ansible-task-as-a-specific-user
